### ISSUE TITLE
integrate our code

### ISSUE THREAD

**Issue by asclepiusaka** [AS-CSLW/AirportSim#1]
upload your code in one directory with your name.
Let's compare different codes and choose one to go on with.

done by 3.30

**Comment by wuchangli** [comment]
ok

**Comment by asclepiusaka** [comment]
I guess we don't need different branchs.
Let's make it easy
git clone it to your local repo.
`git clone https://github.com/AS-CSLW/AirportSim.git`
put all you codes and java class files inside an directory aside from my directory.
add, commit and push it.
