### ISSUE TITLE
Reading candidate implementation and choose one to start working

### ISSUE THREAD

**Issue by asclepiusaka** [AS-CSLW/AirportSim#2]
Since Soowon and Wuchang choose to not share their codes, mine and Xiaoyang's projects is the only ones we have, make some comments in this thread and choose the one you like. Let's begin our work ASAP.

**Comment by wuchangli** [comment]
mxynapoleon

**Comment by mxynapoleon** [comment]
I do not mind use mine. But actually I only get 75 in HW1. I did not complete all required features. I guess we need to sum up and improve the details if you guys made up mind. Anyway let me know what you think.

**Comment by asclepiusaka** [comment]
Actually I get 76 (don't have too much idea about the score :) ). Xiaoyang's code has very nice comment and should be easy to get started wtih. but I think the one event type should be added to include the fact that takeoff also take up runway. (multi runway should be a further step on it)
@soowonch any comment?

**Comment by soowonch** [comment]
I agree. For taking up a runway, isn't it possible of the event "depart_ready" on your(Cong's) code?

**Comment by soowonch** [comment]
Also, how about comparing both UML?

**Comment by wuchangli** [comment]
😆😆😆Mine is 67

**Comment by asclepiusaka** [comment]
decide to go with Xiaoyang's code
